version: '3.2'

services:
  consumer:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: rake run
    environment:
      PUBSUB_EMULATOR_HOST: pubsub_emulator:8681
    depends_on:
      - pubsub_emulator

  pubsub_emulator:
    image: messagebird/gcloud-pubsub-emulator:latest
    environment:
      PUBSUB_PROJECT1: pubsub,test:subscriber
